name: "Release Pipeline"

on:
  push:
    branches:
      - "main"
    paths:
      - "**/*.py"
      - ".github/workflows/*.yml"
      - "poetry.lock"
      - "pyproject.toml"

jobs:
  tests:
    name: Unit-Tests ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs:
      - type
    defaults:
      run:
        shell: sh
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run pytest
        run: poetry run pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./reports/coverage.xml
          flag: unittests-${{ matrix.python-version }}
          fail_ci_if_error: true
