name: "MR Pipeline"

on:
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/ci.yml"
      - ".github/workflows/cd.yml"
      - "poetry.lock"
      - "pyproject.toml"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run ruff linter
        run: poetry run ruff check
      - name: Run ruff formatter
        run: poetry run ruff format --check
  type:
    name: "Type-Check"
    runs-on: ubuntu-latest
    needs:
      - lint
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run mypy
        run: poetry run mypy
  tests:
    name: Unit-Tests ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs:
      - type
    defaults:
      run:
        shell: sh
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run pytest
        run: poetry run pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./reports/coverage.xml
          flags: unittests-${{ matrix.python-version }}
          fail_ci_if_error: true
