name: "Documentation Pipeline"

on:
  pull_request:
    paths:
      - "docs/"
      - ".github/workflows/documentation.yml"
      - "mkdocs.yml"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version-file: "pyproject.toml"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --with doc
      - name: Build the static site
        run: poetry run mkdocs build
